# Generated by Django 5.2.17 on 2026-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
