# Generated by Django 5.2.17 on 2026-09-25 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ai_category_confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
