# Generated by Django 5.2.17 on 2026-09-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_ai_category_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=12)),
                ('sanitized_prompt', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('retrieved_document_ids', models.JSONField(blank=True, default=list)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='tickets.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ai_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tickets.ailog'),
        ),
    ]
