# Generated by Django 5.2.17 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketmessage_is_ai_generated_ticketmessage_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
