# Generated by Django 5.2.17 on 2026-10-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_meta_whatsapp_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoResolutionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_ticket_ids', models.JSONField(blank=True, default=list)),
                ('matched_similarities', models.JSONField(blank=True, default=list)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('generated_response', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('processing', 'Processing'), ('agent_review', 'Agent review'), ('simulation', 'Simulation'), ('auto_send', 'Auto-send'), ('auto_sent', 'Auto-sent')], default='processing', max_length=16)),
                ('decision_reason', models.CharField(blank=True, max_length=160)),
                ('send_status', models.CharField(choices=[('not_sent', 'Not sent'), ('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=16)),
                ('send_error', models.CharField(blank=True, max_length=80)),
                ('send_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_resolution_audits', to='tickets.ailog')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_resolution_audit', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolvedTicketKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField()),
                ('resolution_text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_knowledge', to='tickets.ticket')),
            ],
        ),
    ]
