# Generated by Django 5.2.17 on 2026-10-06 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_auto_resolution_settings(apps, schema_editor):
    settings_model = apps.get_model('tickets', 'AutoResolutionSettings')
    settings_model.objects.using(schema_editor.connection.alias).get_or_create(
        pk=1,
        defaults={
            'enabled': False,
            'email_auto_reply': True,
            'whatsapp_auto_reply': False,
            'simulation_mode': True,
            'minimum_threshold': 0.85,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_autoresolutionaudit_resolvedticketknowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresolutionaudit',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('', 'Unknown')], max_length=16),
        ),
        migrations.AddField(
            model_name='autoresolutionaudit',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='autoresolutionaudit',
            name='provider_result',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='autoresolutionaudit',
            name='selected_match_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoresolutionaudit',
            name='send_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='not_sent', max_length=16),
        ),
        migrations.CreateModel(
            name='AutoResolutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('email_auto_reply', models.BooleanField(default=True)),
                ('whatsapp_auto_reply', models.BooleanField(default=False)),
                ('simulation_mode', models.BooleanField(default=True)),
                ('minimum_threshold', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_resolution_setting_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_auto_resolution_settings, migrations.RunPython.noop),
    ]
