# Generated by Django 5.2.17 on 2026-09-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0003_alter_ticket_ai_category_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=998, unique=True)),
                ('thread_id', models.CharField(blank=True, default='', max_length=998)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='tickets.ticket')),
                ('ticket_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_email', to='tickets.ticketmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/%d/')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_ingestion.inboundemail')),
            ],
        ),
    ]
