# Generated by Django 5.2.17 on 2026-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=255)),
                ('account_fingerprint', models.CharField(max_length=64)),
                ('uid_validity', models.PositiveBigIntegerField()),
                ('last_processed_uid', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('mailbox', 'account_fingerprint'), name='unique_mailbox_account_sync_state'),
                ],
            },
        ),
    ]
